import { test, expect } from '@playwright/test';
import * as fs from 'node:fs';
import * as path from 'node:path';

/**
 * Install wizard: full run, Step 1 (folder permissions) through Step 6
 * (final install submit).
 *
 * Run against a fresh, not-yet-installed instance (e.g. toffee.local right
 * after a rebuild — install/.installed and cfg/config.php removed), the
 * /install/ wizard 403s once install/.installed exists. Point BASE_URL at
 * that instance:
 *
 *   BASE_URL=http://toffee.local npx playwright test install-wizard.spec.ts --headed
 *
 * Window maximizing and slowMo are set in playwright.config.ts (launchOptions),
 * not passable as bare CLI flags, --start-maximized is a Chromium launch arg,
 * not a Playwright CLI option.
 *
 * admin_path and admin_pass are generated by the wizard itself (random),
 * not chosen by this test — they're read back from the live DOM right
 * before the final submit (both fields stay populated even though
 * admin_pass is type="password", .inputValue() still reads it) and written
 * to .last-install.json in this project's root so other spec files/manual
 * runs can pick up this run's real admin credentials without guessing.
 */

test.use({viewport:null, deviceScaleFactor: undefined});

test('install wizard: full install run', async ({ page }) => {

  await page.goto('/install/');
  // Step 1, folder permissions. btn-perm-continue starts disabled and only
  // enables once checkPermissions() resolves ok; Playwright's click()
  // auto-waits for it to become enabled rather than failing immediately.
  await page.click('#btn-perm-continue');

  // Step 2, Root & DB. db_root is prefilled with "root" by default; only
  // the password needs entering per the task.
  await page.fill('#db_rootpw', 'Nafoi111$2');
  await page.click('#btn-test-root');
  // Wait for the verified state (cred-ok becomes visible on success) rather
  // than relying only on fill()'s implicit wait for db_name_create to enable,
  // that would auto-wait for either a real success or a silent stall until
  // timeout, with no clear signal which one happened.
  await page.locator('#cred-ok').waitFor({ state: 'visible' });

  await page.fill('#db_name_create', 'toffee_cart');
  await page.click('#btn-step1-next');

  await page.fill('#db_user', 'toffee_cart');
  // .pw-field-wrap is not unique, step 3 (db_pass), step 4 (admin_pass), and
  // step 5 (admin_path) each have one, all present in the DOM at once. An
  // unscoped selector here would match more than one element; scope to
  // #step-3 so it can only ever hit the db_pass field's own buttons.
  await page.click('#step-3 .pw-field-wrap .btn-gen-pass');
  await page.click('#step-3 .pw-field-wrap .btn-copy-field');

  await page.click('#btn-create-user');

  await page.fill("#admin_user", "toffee_admin")
  await page.fill("#admin_email", "billthetailor@gmail.com")

  await page.click("#step-4 .field .btn-gen-pass")
  await page.click("#step-4 .field .btn-copy-field")
  // admin_confirm is auto-filled to match admin_pass by the generate-password
  // click above (built into the app's own JS), nothing left to do here.

  await page.click("#btn-validate-admin")

  await page.fill("#site_name", "Toffee Lifestyle")
  await page.fill("#site_email", "toffee@gmail.com")

  await page.click("#step-5 .field .btn-copy-field")
  await page.click("#btn-to-install")

  // Step 6 — the actual final submit. btn-to-install (above) only navigates
  // to this step; the wizard's own JS (install/index.php ~line 968) requires
  // a separate click on #btn-install to fire the real "action: install" AJAX
  // call. The earlier version of this test stopped one step short of ever
  // actually completing the install.
  const adminPass = await page.locator('#admin_pass').inputValue();
  const adminPath = await page.locator('#admin_path').inputValue();

  await page.click('#btn-install');
  await page.locator('#step-done').waitFor({ state: 'visible', timeout: 30_000 });

  await expect(page.locator('#step-done')).toBeVisible();

  const credentials = {
    adminUser: 'toffee_admin',
    adminPass,
    adminPath,
    adminEmail: 'billthetailor@gmail.com',
  };
  fs.writeFileSync(
    path.join(__dirname, '..', '.last-install.json'),
    JSON.stringify(credentials, null, 2)
  );
  console.log('Install complete. Credentials written to .last-install.json:', credentials);
});
